site:
  tab: RyuChan
  title: RyuChan
  description: ğŸŒ¸ è½»ç›ˆã€ä¼˜é›…ã€çº¯å‡€ â€”â€” ç”¨æ–‡å­—ä¸å›¾ç‰‡è®°å½•ç”Ÿæ´»ä¸åˆ›æ„
  language: zh
  favicon: /favicon.ico
  theme:
    light: garden
    dark: dracula
    code: github-dark
  date_format: ddd MMM DD YYYY
  blog:
    pageSize: 8
  banner:
    enableRandom: true
    randomUrl: https://t.alcy.cc/lai
    randomCount: 5
    height: 60vh
    images:
      - https://tc.alcy.cc/q/20250908/b2d656670551cb9ea6eda7b46b6c8ec0.webp
  pages:
    home:
      title: RyuChan's Blog
      subtitle: æ¬²ä¹°æ¡‚èŠ±åŒè½½é…’ï¼Œç»ˆä¸ä¼¼ï¼Œå°‘å¹´æ¸¸ï¼
      typewriterTexts:
        - ğŸŒ¸ æ¬²ä¹°æ¡‚èŠ±åŒè½½é…’ï¼Œç»ˆä¸ä¼¼ï¼Œå°‘å¹´æ¸¸ï¼
        - ğŸŒ¸èŠ±æœ‰é‡å¼€æ—¥ï¼Œäººæ— å†å°‘å¹´ï¼
        - ğŸŒ¿ è®°å½•ç”Ÿæ´»çš„ç‚¹æ»´ï¼Œåˆ†äº«ç¾å¥½çš„ç¬é—´ï¼
        - ğŸ“š çº¸ä¸Šå¾—æ¥ç»ˆè§‰æµ…ï¼Œç»çŸ¥æ­¤äº‹è¦èº¬è¡Œï¼
    friend:
      title: å‹äººå¸
      subtitle: è®°å½•é‚£äº›çè´µçš„å‹è°Šï¼Œåˆ†äº«å½¼æ­¤çš„æ•…äº‹
    about:
      title: About Me
      subtitle: ä¸€ä¸ªçƒ­çˆ±ç”Ÿæ´»ä¸æŠ€æœ¯çš„æ™®é€šäººï¼
    navigation:
      title: ç½‘ç«™å¯¼èˆª
      subtitle: æ”¶è—çš„å¸¸ç”¨ç½‘ç«™å’Œå·¥å…·é“¾æ¥
    anime:
      title: è¿½ç•ª
      subtitle: è®°å½•å’Œåˆ†äº«æˆ‘å–œæ¬¢çš„åŠ¨æ¼«ä½œå“
    project:
      title: Projects
      subtitle: å±•ç¤ºä¸€äº›ä¸ªäººæ­å»ºçš„é¡¹ç›®ï¼Œæ¬è¿å·¥ï¼
  menu:
    - id: home
      text: é¦–é¡µ
      href: /
      svg: material-symbols:home-outline-rounded
      target: _self
    - id: write
      text: å†™ä½œ
      href: /write
      svg: material-symbols:edit-square-outline-rounded
      target: _self
    - id: navigation
      text: å¯¼èˆª
      href: /navigation
      svg: material-symbols:explore-outline
      target: _self
    - id: anime
      text: è¿½ç•ª
      href: /anime
      svg: material-symbols:movie-outline
      target: _self
    - id: project
      text: é¡¹ç›®
      href: /project
      svg: material-symbols:code-blocks-outline
      target: _self
    - id: friend
      text: å‹äººå¸
      href: /friend
      svg: material-symbols:supervisor-account-outline-rounded
      target: _self
    - id: about
      text: å…³äº
      href: /about
      svg: material-symbols:info-outline-rounded
      target: _self
anime:
  bilibili:
    uid: '1536411565'
  tmdb:
    apiKey: 08a6bef260044f70c150251c79f2e476
    listId: '8556173'
github:
  owner: kobaridev
  repo: RyuChan
  branch: main
  appId: '-'
  encryptKey: wudishiduomejimo
user:
  name: RyuChan
  site: https://hub.xiaozhangya.xin
  avatar: /images/uploads/1767534109675-0p1nho.jpg
  sidebar:
    social:
      - href: https://github.com/kobaridev
        ariaLabel: Github
        title: Github
        svg: ri:github-line
      - href: https://space.bilibili.com/1536411565
        ariaLabel: BiliBili
        title: BiliBili
        svg: ri:bilibili-line
      - href: https://x.com/xzz_ya
        ariaLabel: Twitter (X)
        title: Twitter (X)
        svg: ri:twitter-line
      - href: https://demo.131714.xyz/rss.xml
        ariaLabel: Subscribe via Folo
        title: RSS
        svg: ri:rss-fill
  footer:
    social:
      - href: https://github.com/kobaridev
        ariaLabel: Github
        title: Github
        svg: ri:github-line
      - href: https://space.bilibili.com/1536411565
        ariaLabel: BiliBili
        title: BiliBili
        svg: ri:bilibili-line
      - href: https://x.com/xzz_ya
        ariaLabel: X(twitter)
        title: X(twitter)
        svg: ri:twitter-line
      - href: https://t.me/xzz_ya
        ariaLabel: Telegram
        title: Telegram
        svg: ri:telegram-line
comments:
  enable: true
  type: giscus
  giscus:
    repo: kobaridev/gsc
    repoId: R_kgDOPTM-mA
    category: General
    categoryId: DIC_kwDOPTM-mM4CtcFq
    mapping: pathname
    lang: zh-CN
    inputPosition: top
    reactionsEnabled: '1'
    emitMetadata: '0'
    loading: lazy
  waline:
    serverURL: https://your-waline-server
    lang: zh-CN
    emoji:
      - https://unpkg.com/@waline/emojis@1.1.0/weibo
      - https://unpkg.com/@waline/emojis@1.1.0/bilibili
    meta:
      - nick
      - mail
      - link
    requiredMeta: []
    reaction: false
    pageview: false
umami:
  enable: false
  baseUrl: https://umami.131714.xyz
  shareId: jToXL5Z3hnA1gKUw
  websiteId: 3f9afc6c-f0bd-4734-be15-6d053960d34d
  timezone: Asia/Shanghai
